version: "3.7"

services:
  # --------> MY-APP-Server <--------
  my-app:
    build:
      context: ../
      dockerfile: ./.docker/node.dockerfile
    image: my-app
    container_name: my-app
    restart: unless-stopped
    working_dir: /usr/src
    env_file: .env
    ports:
      - ${SERVER_PORT}:4000
    volumes:
      - my-app-volume:/usr
    # networks:
    #   - network
    stdin_open: true
    tty: true


  # --------> MY-APP-MONGODB <--------
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file: .env
    # environment:
    #   DB_PASS: ${DB_PASS}
    #   DB_USER: ${DB_USER}
    restart: always
    # networks:
    #   - network
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongodb-volume:/data/db


  # --------> MY-APP-MYSQL <--------
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes:
  #     - mysql-volume:/var/lib/mysql
  #   networks:
  #     - network
  #   env_file:
  #     - .env.docker
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASS}


  # --------> MY-APP-REDIS <--------
  # redis:
  #   container_name: redis
  #   image: "bitnami/redis:latest"
  #   user: "root"
  #   environment:
  #     ALLOW_EMPTY_PASSWORD: "yes"
  #   networks:
  #     - network
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   restart: unless-stopped
  #   volumes:
  #     - ${REDIS_PASS}/redis:/bitnami/redis

# networks:
#   network:
#     external:
#       name: network

volumes:
  my-app-volume:
  mongodb-volume:
  # mysql-volume:
